openapi: 3.1.0
info:
  version: 1.0.0
  title: API
paths:
  /spi/get:
    get:
      tags:
        - spi
      operationId: get
      description: get
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                type: string